name: CI CD

on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  SOURCE_DIR: 'docs'

jobs:

  should_deploy:
    runs-on: ubuntu-latest
    if: "contains( github.event.head_commit.message, '[deploy]')"

  avoid_duplicate_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install MdBook
      run: cargo install mdbook

    - name: Build
      run: mdbook build -d docs

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete

