name: CI CD

on:
  pull_request:
    branches:
    - main

env:
  CARGO_TERM_COLOR: always
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:

  should_deploy:
    runs-on: ubuntu-latest

    steps:
      - if: "startsWith( github.event.head_commit.message, '[deploy]') == false"
        run: exit 0

  avoid_duplicate_workflow:
    needs:
      - should_deploy

    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

  deploy:
    needs:
      - should_deploy

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install MdBook
      run: cargo install mdbook

    - name: Build
      run: mdbook build -d docs

    - name: Deploy
      run: aws s3 sync docs/ s3://$AWS_S3_BUCKET --delete


